import type { Metadata } from "next";
// <<<<<<< resource-page
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// =======
// import { Lora, Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const lora = Lora({
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700"],
//   variable: "--font-lora",
// });

// >>>>>>> dev
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
// <<<<<<< resource-page
//   title: "Create Next App",
//   description: "Generated by create next app",
// =======
//   title: "District 4",
//   description: "Official website for District 4",
// >>>>>>> dev
// };

export default function RootLayout({
  children,
// <<<<<<< resource-page
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
// =======
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en" className={lora.variable}>
//       <body>{children}</body>
// >>>>>>> dev
    </html>
  );
}
